from schemas.action_schema import ActionSchema
from tools.tool_registry import ToolRegistry


class ActionValidator:
    """
    Validates actions generated by the reasoning engine
    before they are executed by tools.
    """

    def __init__(self, tool_registry: ToolRegistry):
        self.tool_registry = tool_registry

    def validate(self, action: ActionSchema) -> bool:
        """
        Validate an action before execution.

        Checks:
        - Action is a valid ActionSchema object
        - Tool name is valid
        - Tool exists in registry
        - Parameters are in dictionary format
        """

        # Validate action object
        if not isinstance(action, ActionSchema):
            raise ValueError(
                "Action must be an instance of ActionSchema."
            )

        # Validate tool name type
        if not isinstance(action.tool_name, str):
            raise ValueError(
                "Tool name must be a string."
            )

        # Validate tool name is not empty
        if not action.tool_name.strip():
            raise ValueError(
                "Tool name cannot be empty."
            )

        # Validate tool exists
        if not self.tool_registry.has_tool(action.tool_name):
            raise ValueError(
                f"Tool '{action.tool_name}' is not registered."
            )

        # Validate parameters type
        if not isinstance(action.parameters, dict):
            raise ValueError(
                "Parameters must be a dictionary."
            )

        return True