from __future__ import annotations

from typing import Any, Dict, List, Optional


class TaskSchema:
    """
    Represents a single executable task generated by the Planner.

    This is the atomic execution unit of the agent.

    Responsibilities:
    - Describe WHAT needs to be accomplished.
    - Specify the capability required.
    - Define expected output.
    - Track execution status.

    NOTE:
    TaskSchema contains NO execution logic.
    It is purely a structured data object.
    """

    VALID_PRIORITIES = {
        "LOW",
        "MEDIUM",
        "HIGH",
    }

    VALID_STATUS = {
        "PENDING",
        "RUNNING",
        "COMPLETED",
        "FAILED",
        "SKIPPED",
    }

    def __init__(
        self,
        task_id: int,
        description: str,
        capability_required: str,
        expected_output: str,
        completion_criteria: str,
        dependencies: Optional[List[int]] = None,
        priority: str = "MEDIUM",
        status: str = "PENDING",
        metadata: Optional[Dict[str, Any]] = None,
    ):

        if not description:
            raise ValueError("Task description cannot be empty.")

        if not capability_required:
            raise ValueError("Capability required cannot be empty.")

        if priority not in self.VALID_PRIORITIES:
            raise ValueError(
                f"Invalid priority '{priority}'. "
                f"Expected one of {self.VALID_PRIORITIES}"
            )

        if status not in self.VALID_STATUS:
            raise ValueError(
                f"Invalid status '{status}'. "
                f"Expected one of {self.VALID_STATUS}"
            )

        self.task_id = task_id
        self.description = description
        self.capability_required = capability_required
        self.expected_output = expected_output
        self.completion_criteria = completion_criteria

        self.dependencies = dependencies or []

        self.priority = priority
        self.status = status

        self.metadata = metadata or {}

    def mark_running(self):
        self.status = "RUNNING"

    def mark_completed(self):
        self.status = "COMPLETED"

    def mark_failed(self):
        self.status = "FAILED"

    def mark_skipped(self):
        self.status = "SKIPPED"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "description": self.description,
            "capability_required": self.capability_required,
            "expected_output": self.expected_output,
            "completion_criteria": self.completion_criteria,
            "dependencies": self.dependencies,
            "priority": self.priority,
            "status": self.status,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TaskSchema":
        return cls(
            task_id=data.get("task_id"),
            description=data.get("description", ""),
            capability_required=data.get(
                "capability_required",
                "",
            ),
            expected_output=data.get(
                "expected_output",
                "",
            ),
            completion_criteria=data.get(
                "completion_criteria",
                "",
            ),
            dependencies=data.get(
                "dependencies",
                [],
            ),
            priority=data.get(
                "priority",
                "MEDIUM",
            ),
            status=data.get(
                "status",
                "PENDING",
            ),
            metadata=data.get(
                "metadata",
                {},
            ),
        )

    def __repr__(self) -> str:
        return (
            f"TaskSchema("
            f"task_id={self.task_id}, "
            f"description='{self.description}', "
            f"capability_required='{self.capability_required}', "
            f"priority='{self.priority}', "
            f"status='{self.status}')"
        )

    __str__ = __repr__