from schemas.action_schema import ActionSchema
from schemas.observation_schema import ObservationSchema
from tools.tool_registry import ToolRegistry


class ToolExecutor:
    """
    Responsible for executing validated actions using the
    appropriate tool and converting the result into an observation.
    """

    def __init__(self, tool_registry: ToolRegistry):
        self.tool_registry = tool_registry

    def execute(self, action: ActionSchema) -> ObservationSchema:
        """
        Execute an action and return an observation.

        Parameters:
            action: ActionSchema object generated by the reasoning engine.

        Returns:
            ObservationSchema containing the execution result.
        """

        try:
            # Retrieve tool from registry
            tool = self.tool_registry.get_tool(
                action.tool_name
            )

            # Execute tool with parameters
            result = tool.execute(
                action.parameters
            )

            # Create successful observation
            return ObservationSchema(
                tool_name=action.tool_name,
                success=True,
                result=result,
                error=None
            )

        except Exception as e:
            # Create failed observation
            return ObservationSchema(
                tool_name=action.tool_name,
                success=False,
                result=None,
                error=str(e)
            )